version: "25.0.3"

services:
  sqlserver:    
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    networks:
      - tshoes-bridge
    ports:
      - 1433:1433
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Senha@123"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmqTShoes
    networks:
      - tshoes-bridge
    ports:
      - 15672:15672
      - 5672:5672

  ocelot:
    image: api-gateway/app:1.0
    container_name: ocelot
    networks:
      - tshoes-bridge
    ports:
      - 8080:80

  product:
    image: product-service/app:1.0
    container_name: product-service
    networks:
      - tshoes-bridge
    ports:
      - 3000:80
      
  cart:
    image: cart-service/app:1.0
    container_name: cart-service
    networks:
      - tshoes-bridge
    ports:
      - 3001:80
    depends_on:
      - rabbitmq
      
  order:
    image: order-service/app:1.0
    container_name: order-service
    networks:
      - tshoes-bridge
    ports:
      - 3002:80
    depends_on:
      - rabbitmq

  payment:
    image: payment-service/app:1.0
    container_name: payment-service
    networks:
      - tshoes-bridge
    ports:
      - 3003:80
    depends_on:
      - rabbitmq

  identity:
    image: identity-server/app:1.0
    container_name: identity-server
    networks:
      - tshoes-bridge
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    ports:
      - 3004:80

  web: 
    image: tshoes-web/app:1.0
    container_name: tshoes-web    
    networks:
      - tshoes-bridge
    ports:
      - 5000:80
    volumes:
      - webvolume:/usr/share/nginx/html

networks:
  tshoes-bridge:
    driver: bridge

volumes:
  sqlvolume:
  webvolume:
