services:
  sqlserver:    
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    networks:
      - tshoes-bridge
    ports:
      - 1433:1433
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Senha@123"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmqTShoes
    networks:
      - tshoes-bridge
    ports:
      - 15672:15672
      - 5672:5672

  ocelot:
    build: 
      context: ./Ecommerce.APIGateway
    image: guijs02/api-gateway:1.1
    container_name: ocelot
    hostname: ocelot
    networks:
      - tshoes-bridge
    ports:
      - 8080:80

  product:
    build: 
      context: ./EcommerceProductAPI
    image: guijs02/product-service:1.0
    container_name: product-service
    hostname: product-service
    networks:
      - tshoes-bridge
    ports:
      - 3000:80
      
  cart:
    build: 
      context: ./EcommerceCartAPI
    image: guijs02/cart-service:1.0
    container_name: cart-service
    hostname: cart-service
    networks:
      - tshoes-bridge
    ports:
      - 3001:80
    depends_on:
      - rabbitmq
      
  order:
    build: 
      context: ./EcommerceOrderAPI
    image: guijs02/order-service:1.0
    container_name: order-service
    hostname: order-service
    networks:
      - tshoes-bridge
    ports:
      - 3002:80
    depends_on:
      - rabbitmq
    restart: on-failure
    

  payment:
    build: 
      context: ./EcommercePaymentAPI
    image: guijs02/payment-service:1.0
    container_name: payment-service
    hostname: payment-service
    networks:
      - tshoes-bridge
    ports:
      - 3003:80
    depends_on:
      - rabbitmq
    restart: on-failure

  identity:
    build: 
      context: ./IdentityServer
    image: guijs02/identity-server:1.0
    container_name: identity-server
    hostname: identity-server
    networks:
      - tshoes-bridge
    ports:
      - 3004:80

  web: 
    build: 
      context: ./EcommerceTShoes
    image: guijs02/tshoes-web:1.0
    container_name: tshoes-web    
    hostname: tshoes-web    
    networks:
      - tshoes-bridge
    ports:
      - 5000:80

networks:
  tshoes-bridge:
    driver: bridge

volumes:
  sqlvolume:
